import React from "react";
import ReactMarkdown from "react-markdown";
import { Download, X } from "lucide-react";
import jsPDF from "jspdf";

export default function SummaryPanel({
  summary,
  title = "Document Title",
  isOpen,
  onClose,
}) {
  const handleDownloadPDF = () => {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();
    const margin = 20;
    const maxLineWidth = pageWidth - margin * 2;
    let yPos = margin;

    const colorPrimary = [79, 70, 229]; // Indigo-600
    const colorTitle = [15, 23, 42]; // Slate-900
    const colorHeading = [30, 41, 59]; // Slate-800
    const colorBody = [51, 65, 85]; // Slate-700
    const colorAccent = [226, 232, 240]; // Slate-200

    const cleanMarkdown = (text) => {
      return text
        .replace(/\*\*(.*?)\*\*/g, "$1")
        .replace(/\*(.*?)\*/g, "$1")
        .replace(/_(.*?)_/g, "$1")
        .replace(/`{1,3}(.*?)`{1,3}/g, "$1")
        .replace(/\[(.*?)\]\(.*?\)/g, "$1")
        .replace(/^-\s+/, "")
        .replace(/^\*\s+/, "");
    };

    // Add Header
    const addHeader = (docInstance, pageNumber) => {
      docInstance.setFillColor(...colorPrimary);
      docInstance.rect(0, 0, pageWidth, 20, "F");

      docInstance.setTextColor(255, 255, 255);
      docInstance.setFontSize(16);
      docInstance.setFont("helvetica", "bold");
      docInstance.text("Research Paper Summary", margin, 13);

      docInstance.setFontSize(10);
      docInstance.setFont("helvetica", "normal");
      const dateStr = new Date().toLocaleDateString();
      docInstance.text(dateStr, pageWidth - margin, 13, { align: "right" });
    };

    // Add Footer
    const addFooter = (docInstance, pageNumber) => {
      docInstance.setDrawColor(200, 200, 200);
      docInstance.line(
        margin,
        pageHeight - 15,
        pageWidth - margin,
        pageHeight - 15
      );

      docInstance.setFontSize(9);
      docInstance.setTextColor(100, 100, 100);
      docInstance.text(`Generated by ScholarSense AI`, margin, pageHeight - 10);
      docInstance.text(
        `Page ${pageNumber}`,
        pageWidth - margin,
        pageHeight - 10,
        { align: "right" }
      );
    };

    // Check Page Break
    let pageCount = 1;
    const checkPageBreak = (neededSpace) => {
      if (yPos + neededSpace > pageHeight - 25) {
        doc.addPage();
        pageCount++;
        yPos = 35;
        addHeader(doc, pageCount);
        addFooter(doc, pageCount);
        return true;
      }
      return false;
    };

    // Start Document
    addHeader(doc, pageCount);
    addFooter(doc, pageCount);
    yPos = 40;

    //  Main Title
    doc.setTextColor(...colorTitle);
    doc.setFontSize(22);
    doc.setFont("helvetica", "bold");

    const cleanTitle = cleanMarkdown(title);
    const titleLines = doc.splitTextToSize(cleanTitle, maxLineWidth);
    doc.text(titleLines, margin, yPos);

    yPos += titleLines.length * 10 + 5;

    // Separator Line
    doc.setDrawColor(...colorAccent);
    doc.setLineWidth(0.5);
    doc.line(margin, yPos, pageWidth - margin, yPos);
    yPos += 15;

    // Process Summary Content
    const rawLines = (summary || "No summary available.").split("\n");

    rawLines.forEach((line) => {
      const trimmedLine = line.trim();
      if (!trimmedLine) {
        yPos += 5;
        return;
      }

      const displayText = cleanMarkdown(trimmedLine);

      if (trimmedLine.startsWith("#")) {
        doc.setFont("helvetica", "bold");
        doc.setTextColor(...colorHeading);

        const isMainHeading = trimmedLine.startsWith("# ");
        const fontSize = isMainHeading ? 14 : 13;
        doc.setFontSize(fontSize);

        const lineHeight = fontSize * 0.5 + 4;
        checkPageBreak(lineHeight + 8);

        yPos += 5;
        doc.text(displayText.replace(/^#+\s*/, ""), margin, yPos);
        yPos += lineHeight + 2;
      } else if (trimmedLine.startsWith("- ") || trimmedLine.startsWith("* ")) {
        doc.setFont("helvetica", "normal");
        doc.setTextColor(...colorBody);
        doc.setFontSize(11);

        const lineHeight = 6;
        const indent = 5;
        const bulletLineWidth = maxLineWidth - indent;

        const wrappedLines = doc.splitTextToSize(displayText, bulletLineWidth);

        checkPageBreak(wrappedLines.length * lineHeight);

        doc.text("•", margin, yPos);
        wrappedLines.forEach((wrappedLine) => {
          doc.text(wrappedLine, margin + indent, yPos);
          yPos += lineHeight;
        });
        yPos += 2;
      } else {
        doc.setFont("helvetica", "normal");
        doc.setTextColor(...colorBody);
        doc.setFontSize(11);

        const lineHeight = 6;
        const wrappedLines = doc.splitTextToSize(displayText, maxLineWidth);

        checkPageBreak(wrappedLines.length * lineHeight);

        wrappedLines.forEach((wrappedLine) => {
          doc.text(wrappedLine, margin, yPos);
          yPos += lineHeight;
        });
        yPos += 3;
      }
    });

    doc.save("scholar_sense_summary.pdf");
  };

  return (
    <div
      className={`
        fixed inset-y-0 right-0 z-40 w-96 bg-white/95 backdrop-blur-xl border-l border-slate-200 
        transform transition-transform duration-300 ease-in-out shadow-2xl
        ${isOpen ? "translate-x-0" : "translate-x-full"}
      `}
    >
      {/* Header Area */}
      <div className="p-6 border-b border-slate-200 flex items-center justify-between bg-slate-50/50">
        <h3 className="text-xs font-bold text-slate-500 uppercase tracking-wider">
          Summary
        </h3>
        <div className="flex items-center gap-2">
          {summary && (
            <button
              onClick={handleDownloadPDF}
              className="p-1.5 bg-indigo-50 hover:bg-indigo-100 text-indigo-600 rounded-lg transition-all"
              title="Download PDF"
            >
              <Download className="w-4 h-4" />
            </button>
          )}
          <button
            onClick={onClose}
            className="p-1.5 hover:bg-slate-100 text-slate-400 hover:text-slate-700 rounded-lg transition-all"
          >
            <X className="w-4 h-4" />
          </button>
        </div>
      </div>

      {/* Content Area */}
      <div className="h-[calc(100vh-80px)] overflow-y-auto p-6 custom-scrollbar">
        {/* Removed prose-invert so text is dark */}
        <div className="prose prose-sm prose-slate max-w-none">
          <div className="markdown-body text-xs text-slate-600 leading-relaxed">
            <ReactMarkdown>{summary}</ReactMarkdown>
          </div>
        </div>
      </div>
    </div>
  );
}
