import React from "react";
import ReactMarkdown from "react-markdown";
import { Download } from "lucide-react";
import jsPDF from "jspdf";

export default function SummaryPanel({ summary, title = "Document Title" }) {
  const handleDownloadPDF = () => {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();
    const margin = 20;
    const maxLineWidth = pageWidth - margin * 2;
    let yPos = margin;

    // --- Premium Color Palette ---
    const colorPrimary = [79, 70, 229]; // Indigo-600 (Header Background)
    const colorTitle = [0, 0, 0]; // Pure Black (Main Title)
    const colorHeading = [20, 20, 20]; // Off-Black (Headings - Sharp & Dark)
    const colorBody = [0, 0, 0]; // Pure Black (Body Text - Max Readability)
    const colorAccent = [200, 200, 200]; // Light Grey (Divider lines)

    // --- Helper: Clean Markdown Symbols ---
    // Removes **, *, _, `, []() to make text readable
    const cleanMarkdown = (text) => {
      return text
        .replace(/\*\*(.*?)\*\*/g, "$1") // Remove bold syntax (**text**)
        .replace(/\*(.*?)\*/g, "$1") // Remove italic syntax (*text*)
        .replace(/_(.*?)_/g, "$1") // Remove underscore italics (_text_)
        .replace(/`{1,3}(.*?)`{1,3}/g, "$1") // Remove code ticks
        .replace(/\[(.*?)\]\(.*?\)/g, "$1") // Remove links, keep label
        .replace(/^-\s+/, "") // Remove bullet point markers for processing
        .replace(/^\*\s+/, ""); // Remove asterisk markers for processing
    };

    // --- Helper: Add Header ---
    const addHeader = (docInstance, pageNumber) => {
      docInstance.setFillColor(...colorPrimary);
      docInstance.rect(0, 0, pageWidth, 20, "F");

      docInstance.setTextColor(255, 255, 255);
      docInstance.setFontSize(16);
      docInstance.setFont("helvetica", "bold");
      docInstance.text("Research Paper Summary", margin, 13);

      docInstance.setFontSize(10);
      docInstance.setFont("helvetica", "normal");
      const dateStr = new Date().toLocaleDateString();
      docInstance.text(dateStr, pageWidth - margin, 13, { align: "right" });
    };

    // --- Helper: Add Footer ---
    const addFooter = (docInstance, pageNumber) => {
      docInstance.setDrawColor(200, 200, 200);
      docInstance.line(
        margin,
        pageHeight - 15,
        pageWidth - margin,
        pageHeight - 15
      );

      docInstance.setFontSize(9);
      docInstance.setTextColor(100, 100, 100);
      docInstance.text(`Generated by ScholarSense AI`, margin, pageHeight - 10);
      docInstance.text(
        `Page ${pageNumber}`,
        pageWidth - margin,
        pageHeight - 10,
        { align: "right" }
      );
    };

    // --- Helper: Check Page Break ---
    let pageCount = 1;
    const checkPageBreak = (neededSpace) => {
      if (yPos + neededSpace > pageHeight - 25) {
        doc.addPage();
        pageCount++;
        yPos = 35; // Reset Y below header
        addHeader(doc, pageCount);
        addFooter(doc, pageCount);
        return true;
      }
      return false;
    };

    // --- 1. Start Document ---
    addHeader(doc, pageCount);
    addFooter(doc, pageCount);
    yPos = 40;

    // --- 2. Main Title ---
    doc.setTextColor(...colorTitle);
    doc.setFontSize(22);
    doc.setFont("helvetica", "bold");

    // Clean title just in case
    const cleanTitle = cleanMarkdown(title);
    const titleLines = doc.splitTextToSize(cleanTitle, maxLineWidth);
    doc.text(titleLines, margin, yPos);

    yPos += titleLines.length * 10 + 5;

    // Separator Line
    doc.setDrawColor(...colorAccent);
    doc.setLineWidth(0.5);
    doc.line(margin, yPos, pageWidth - margin, yPos);
    yPos += 15;

    // --- 3. Process Summary Content ---
    const rawLines = (summary || "No summary available.").split("\n");

    rawLines.forEach((line) => {
      const trimmedLine = line.trim();
      if (!trimmedLine) {
        yPos += 5; // Space for empty lines
        return;
      }

      // Clean the text of markdown symbols for rendering
      const displayText = cleanMarkdown(trimmedLine);

      if (trimmedLine.startsWith("#")) {
        // --- HEADING DETECTION (#) ---
        doc.setFont("helvetica", "bold");
        doc.setTextColor(...colorHeading); // Deep Navy

        // Size logic: H1 (#) vs H2 (##)
        const isMainHeading = trimmedLine.startsWith("# ");
        const fontSize = isMainHeading ? 14 : 13;
        doc.setFontSize(fontSize);

        const lineHeight = fontSize * 0.5 + 4;
        checkPageBreak(lineHeight + 8);

        yPos += 5; // Spacing before heading
        doc.text(displayText.replace(/^#+\s*/, ""), margin, yPos);
        yPos += lineHeight + 2;
      } else if (trimmedLine.startsWith("- ") || trimmedLine.startsWith("* ")) {
        // --- BULLET POINT DETECTION (-, *) ---
        doc.setFont("helvetica", "normal");
        doc.setTextColor(...colorBody);
        doc.setFontSize(11);

        const lineHeight = 6;
        // Indent text, add bullet symbol
        const indent = 5;
        const bulletLineWidth = maxLineWidth - indent;

        const wrappedLines = doc.splitTextToSize(displayText, bulletLineWidth);

        checkPageBreak(wrappedLines.length * lineHeight);

        // Draw Bullet
        doc.text("•", margin, yPos);

        // Draw Text (Indented)
        wrappedLines.forEach((wrappedLine) => {
          doc.text(wrappedLine, margin + indent, yPos);
          yPos += lineHeight;
        });
        yPos += 2;
      } else {
        // --- STANDARD PARAGRAPH ---
        doc.setFont("helvetica", "normal");
        doc.setTextColor(...colorBody);
        doc.setFontSize(11);

        const lineHeight = 6;
        const wrappedLines = doc.splitTextToSize(displayText, maxLineWidth);

        checkPageBreak(wrappedLines.length * lineHeight);

        wrappedLines.forEach((wrappedLine) => {
          doc.text(wrappedLine, margin, yPos);
          yPos += lineHeight;
        });
        yPos += 3; // Gap between paragraphs
      }
    });

    // --- 4. Save ---
    doc.save("scholar_sense_summary.pdf");
  };

  return (
    <div className="hidden xl:flex flex-col w-120 border-l border-slate-800 bg-slate-900/50 h-full">
      {/* Header Area of Panel */}
      <div className="p-6 border-b border-slate-800/50 flex items-center justify-between bg-slate-900/80 backdrop-blur-md">
        <h3 className="text-xs font-bold text-indigo-400 uppercase tracking-wider">
          Executive Summary
        </h3>
        {summary && (
          <button
            onClick={handleDownloadPDF}
            className="p-1.5 bg-indigo-600/10 hover:bg-indigo-600 text-indigo-400 hover:text-white rounded-lg transition-all"
            title="Download PDF"
          >
            <Download className="w-4 h-4" />
          </button>
        )}
      </div>

      {/* Content Area */}
      <div className="flex-1 overflow-y-auto p-6 custom-scrollbar">
        <div className="prose prose-invert prose-sm prose-slate max-w-none">
          <div className="markdown-body text-xs text-slate-400 leading-relaxed">
            <ReactMarkdown>{summary}</ReactMarkdown>
          </div>
        </div>
      </div>
    </div>
  );
}
